name: example
description: A usage example of flutter_typeahead

dependencies:
  flutter:
    sdk: flutter

  flutter_typeahead_web:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true