name: flutter_typeahead_web
version: 1.0.0+1

description: A highly customizable typeahead (autocomplete) text input field for Flutter with web support
homepage: https://github.com/sarbagyastha/flutter_typeahead
author: Sarbagya Dhaubanjar <github@sarbagyastha.com.np>

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.5.0 <3.0.0'